### ISSUE TITLE
Doughnut inner option ignored

### ISSUE THREAD

**Issue by vypsim** [serjilyashenko/react-simple-pie#11]
Hi, first of all, thanks for a great library.

I've upgraded from version `~1.1.0` to `~1.3.5` and calling `simpleDoughnut([...], { pallet: [...], inner: 0.75, borderWidth: 0})` is producing doughnuts with thicker borders, the `inner` option doesn't seem to have an effect if I change it.

**Comment by serjilyashenko** [comment]
Hi, @vypsim
Thank you for the feedback. Much appreciated.

I've prepared a fix for the issue and will release a new version shortly.

**Comment by vypsim** [comment]
Tested and it works perfectly! thanks for the super quick turn around 🚀

**Comment by serjilyashenko** [comment]
simple-pie@1.3.6 🚀
